development:
  :concurrency: 5

production:
  :concurrency: 1

:max_retries: 1

:queues:
  - default
  - mailers
  - greyrepo_production_default
  - greyrepo_production_mailers
  - greyrepo_development_default
  - greyrepo_development_mailers
